server:
  port: ${PORT:8443}
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: config/ssl/key-store.pfx
    key-store-password: storepass
    trust-store-type: PKCS12
    trust-store: config/ssl/trust-store.pfx
    trust-store-password: storepass
    # need
    client-auth: want

security:
  headers:
    hsts: NONE

app:
  route:
    api: ${API:/api/v1}
  proxy:
    enabled: false
    host: my.proxy
    port: 80
  certificates-enable:

spring:
  #main:
  #  web-application-type: reactive
  profiles:
    active: dev
  messages:
    basename: i18n/messages
    encoding: UTF-8
  application:
    name: checkout-company-api

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: loggers
    #beans:
    #  cache:
    #    time-to-live: 10s
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export: 
        enabled: true
  server:
    port: 8091
    address: 127.0.0.1
    base-path: /
  security:
    enabled: false

# https://www.baeldung.com/spring-boot-info-actuator-custom
info:
  app:
    name: checkout-company-api
  environment: desarrollo
  
logging:
  file: logs/checkout-company-api.log
  level:
    root: INFO
